language: android
jdk:
    - oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.1.2
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  # Install base Android SDK
    - sudo apt-get update -qq
    - sudo apt-get install -qq libstdc++6:i386 lib32z1 build-essential autoconf automake libtool expect
    - curl -L http://dl.google.com/android/ndk/android-ndk-r9-linux-x86_64.tar.bz2 > ndk.tar.bz2
    - sudo tar -C /opt -jxf ndk.tar.bz2
    - export NDK_PROJECT_PATH=$PWD
    - chmod +x gradlew

script:
    - make -C external NDK=/opt/android-ndk-r9
    - ./gradlew clean assembleDebug
